Repository DZoltan/MyBlogProject-miniproject, pull requests merged in 2021-09, with the labels that each got.

#5 KovSpec: Vagyalom, igényelt üzl.foly.mod. új funkció
  Dokumentumok/kovetelmenyspecifikacio.md
Labels: documentation

#8 FunSpec: update
  Dokumentumok/funkciospecifikacio.md
Labels: documentation

#12 KövSpec: Jelenlegi üzleti folyamatok modellje
  Dokumentumok/kovetelmenyspecifikacio.md
Labels: documentation

#13 KovSpec: Formai korrekció
  Dokumentumok/kovetelmenyspecifikacio.md
Labels: documentation

#20 FuncSpec: Jelenlegi üzleti folyamatok modellje
  Dokumentumok/funkciospecifikacio.md
Labels: documentation

#41 like & dislike eltávolítva a funktervből
  Dokumentumok/rendszerterv.md
Labels: invalid

#46 Update rendszerterv.md
  Dokumentumok/rendszerterv.md
Labels: documentation

#51 Update rendszerterv.md
  Dokumentumok/rendszerterv.md
Labels: bug, documentation

#54 Fejlesztés elkezdve, megjelenés
  firstGUI/.idea/.gitignore
  firstGUI/.idea/compiler.xml
  firstGUI/.idea/jarRepositories.xml
  firstGUI/.idea/misc.xml
  firstGUI/.idea/runConfigurations.xml
  firstGUI/.idea/uiDesigner.xml
  firstGUI/.idea/vcs.xml
  firstGUI/pom.xml
  firstGUI/src/main/java/UIElements/Button.java
  firstGUI/src/main/java/View/MainWindow.java
  firstGUI/src/main/java/main/Main.java
Labels: enhancement

#56 FX verzió feltöltve - megbeszélésre vár
  MyBlog-FX/.idea/.gitignore
  MyBlog-FX/.idea/compiler.xml
  MyBlog-FX/.idea/jarRepositories.xml
  MyBlog-FX/.idea/misc.xml
  MyBlog-FX/.idea/runConfigurations.xml
  MyBlog-FX/pom.xml
  MyBlog-FX/src/main/java/BlogStart.java
  MyBlog-FX/src/main/java/Controller/PostController.java
  MyBlog-FX/src/main/java/Main.java
  MyBlog-FX/src/main/java/UIElements/NodePanel.java
  MyBlog-FX/src/main/resources/fxs/mainWindow.fxml
  MyBlog-FX/target/classes/fxs/mainWindow.fxml
  firstGUI/src/main/java/UIElements/SlidePanel.java
Labels: help wanted

#63 Post és Comment modell osztály & JSON példa fájl
  MyBlog-FX/.idea/runConfigurations.xml
  MyBlog-FX/pom.xml
  MyBlog-FX/sample.json
  MyBlog-FX/src/main/java/Model/Comment.java
  MyBlog-FX/src/main/java/Model/Main.java
  MyBlog-FX/src/main/java/Model/Post.java
Labels: enhancement

#65 duplikált build a pomban javítva
  MyBlog-FX/.idea/runConfigurations.xml
  MyBlog-FX/pom.xml
Labels: bug

#70 Egy üzenet megnyitása egy új ablakban történik
  MyBlog-FX/src/main/java/Controller/CommentController.java
  MyBlog-FX/src/main/java/UIElements/KommentPanel.java
  MyBlog-FX/src/main/java/UIElements/NodePanel.java
  MyBlog-FX/src/main/resources/fxs/post.fxml
  MyBlog-FX/target/classes/fxs/post.fxml
  MyBlog-FX/target/classes/imgs/back.png
Labels: enhancement

#72 Üzenet ablak megszerkesztve
  MyBlog-FX/src/main/resources/fxs/postWindow.fxml
Labels: enhancement

#76 Üzenet ablak szerekesztés elkezdve
  MyBlog-FX/src/main/java/Controller/CommentController.java
  MyBlog-FX/src/main/java/Controller/PostController.java
  MyBlog-FX/src/main/java/UIElements/KommentPanel.java
  MyBlog-FX/src/main/java/UIElements/NodePanel.java
Labels: enhancement

#82 Posztok létrehozhatóak, gombok bekötve
  MyBlog-FX/sample.json
  MyBlog-FX/src/main/java/BlogStart.java
  MyBlog-FX/src/main/java/Controller/PostController.java
  MyBlog-FX/src/main/java/Model/Main.java
  MyBlog-FX/src/main/java/Model/Post.java
  MyBlog-FX/src/main/java/UIElements/NodePanel.java
  MyBlog-FX/src/main/resources/fxs/mainWindow.fxml
  MyBlog-FX/target/classes/fxs/mainWindow.fxml
Labels: enhancement

#83 ListDialog hozzáadása
  MyBlog-FX/src/main/java/Controller/PostController.java
Labels: enhancement

#89 Üzenet korrekció: Új üzenet létrejön ha van cím és leírás. Dátum és s…
  MyBlog-FX/sample.json
  MyBlog-FX/src/main/java/Controller/PostController.java
  MyBlog-FX/src/main/java/UIElements/NodePanel.java
  MyBlog-FX/target/classes/fxs/postWindow.fxml
Labels: enhancement

#94 Keresés státusz alapján
  MyBlog-FX/sample.json
  MyBlog-FX/src/main/java/Controller/PostController.java
  MyBlog-FX/src/main/java/Model/Status.java
Labels: enhancement

#97 JUnit Test NodePanel init teszt
  MyBlog-FX/pom.xml
  MyBlog-FX/src/main/java/UIElements/NodePanel.java
  MyBlog-FX/src/test/java/UIElementTest/NodePanelTest.java
Labels: test
